baseURL = 'https://example.org/'
languageCode = 'zh-TW'
title = '【揚琴】亖亖 f.f.'
theme = 'mainroad'

#summaryLength = 1 # minimum summary words, but chinese is always together, so it means minimum summary paragraph for chinese
[Author] # Used in authorbox
  name = "亖亖"
  bio = "無聊當有趣"

[Params]
  highlightColor = "#afc5cf"
  copyright = "亖亖"
  opengraph = true # show contents when share from other social media eg. FB
  schema = true # let browser understand stucture of my website
  twitter_cards = true # opengraph for twitter
  readmore = false
  # toc = true # table of contents on the up sction of website
  pager = true
  mainSections = ["work", "news", "blog", "article"]
  #post_meta = ["work", "news", "blog", "article"]

[Params.logo]
  image = "img/MyLogo.jpg"
  subtitle = false
  
[Params.widgets]
  recent_num = 3

[Params.widgets.social]
  github = "nufneb"
  # email = "152yg@protonmail.com"

[[Params.widgets.social.custom]]
  title = "YouTube"
  url = "https://www.youtube.com/channel/UCfJl2j_10-oaTUqm0VGbfBw"

[Params.sidebar]
  home = "right"
  single = false
  widgets = ["search", "recent", "categories", "taglist", "social"]
